"""empty message

Revision ID: 05967cc7f7cd
Revises: cf37025d3b4f
Create Date: 2018-03-04 17:52:47.711697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05967cc7f7cd'
down_revision = 'cf37025d3b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('property', sa.Column('add_opt', sa.Text(), nullable=True))
    op.add_column('property', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('property', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('property', sa.Column('room_type', sa.String(length=50), nullable=True))
    op.add_column('property', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('property', sa.Column('zip_code', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'property', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'zip_code')
    op.drop_column('property', 'state')
    op.drop_column('property', 'room_type')
    op.drop_column('property', 'country')
    op.drop_column('property', 'city')
    op.drop_column('property', 'category')
    op.drop_column('property', 'add_opt')
    op.drop_table('subcategory')
    op.drop_table('category')
    # ### end Alembic commands ###
