"""empty message

Revision ID: 0613585dcff1
Revises: f94c154af3b7
Create Date: 2018-03-05 18:52:24.595340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0613585dcff1'
down_revision = 'f94c154af3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('bathroom_cnt', sa.String(length=5), nullable=True))
    op.drop_column('property', 'bethroom_cnt')
    op.drop_column('property', 'accomodates_cnt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('accomodates_cnt', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('property', sa.Column('bethroom_cnt', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('property', 'bathroom_cnt')
    # ### end Alembic commands ###
