"""empty message

Revision ID: 3e1067d10d83
Revises: 0613585dcff1
Create Date: 2018-03-05 19:12:04.794054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1067d10d83'
down_revision = '0613585dcff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('google_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'google_address')
    # ### end Alembic commands ###
