"""empty message

Revision ID: d43151b344d6
Revises: 05967cc7f7cd
Create Date: 2018-03-04 23:32:23.375921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43151b344d6'
down_revision = '05967cc7f7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('space_for', sa.String(length=10), nullable=True))
    op.add_column('property', sa.Column('subcategory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'subcategory')
    op.drop_column('property', 'space_for')
    # ### end Alembic commands ###
